development:
    host: localhost
    port: 27017
    database: loca_development
    logger: true

staging:
    host: localhost
    port: 27017
    database: loca_staging
    logger: true
    username: loca
    password: notdifficult

test:
    host: localhost
    port: 27017
    database: loca_test
    logger: true

production:
    host: localhost
    port: 27017
    database: loca
    logger: false
    #username: baanling
    #password: somedifficultpassword34324
